version: "3.9"
services:
  kinokuniya-soap-service-web:
    image: kino-soap:latest
    ports:
      - 8001:8001
    hostname: kinokuniya-soap-service
    env_file: .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - kinokuniya-soap-service-db
    networks:
      - kinokuniya-network
  kinokuniya-soap-service-db:
    image: mysql:latest
    ports:
      - 3309:3306
    env_file: .env
    hostname: kinokuniya-soap-db
  networks:
      - kinokuniya-network
volumes:
  db:
    driver: local
