version: '3.8'
services:
  soapservice:
    container_name: kinokuniya-jax-ws
    build: .
    ports:
      - "8001:8001"
    env_file: .env
    volumes:
      - .:/usr/src/app
  mysqlsoap:
    container_name: db-soapservice
    image: mysql:latest
    ports:
      - "3309:3306"
    env_file: .env
    hostname: db-soap-service
    volumes:
      - ./db:/var/lib/mysql
volumes:
  db:
    driver: local
